### ISSUE TITLE
jest tests fail

### ISSUE THREAD

**Issue by zindel** [fastpack/fastpack#29]
@TrySound, could you please look into this? It looks like we need sorting when collecting stats.

```
$ /Users/zindel/ocaml/fastpack/test/node_modules/.bin/jest
 PASS  transpile-builtin/transpile-builtin.test.js
 FAIL  stats-json/stats-json.test.js
  ● --stats=json add modulesPaths in prod

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

      Object {
        "modulesPaths": Array [
    +     "./dep2.js",
          "./dep1.js",
    -     "./dep2.js",
          "./index.js",
        ],
      }

      11 |       })
      12 |     )
    > 13 |   ).toMatchSnapshot();
      14 | });
      15 |
      16 | test('--stats=json add modulesPaths in dev', async () => {

      at Object.<anonymous>.test (stats-json/stats-json.test.js:13:3)

  ● --stats=json add modulesPaths in dev

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

      Object {
        "modulesPaths": Array [
    +     "./dep2.js",
          "./dep1.js",
    -     "./dep2.js",
          "./index.js",
        ],
      }

      23 |       })
      24 |     )
    > 25 |   ).toMatchSnapshot();
      26 | });
      27 |

      at Object.<anonymous>.test (stats-json/stats-json.test.js:25:3)

 › 2 snapshot tests failed.
Snapshot Summary
 › 2 snapshot tests failed in 1 test suite. Inspect your code changes or re-run jest with `-u` to update them.

Test Suites: 1 failed, 1 passed, 2 total
Tests:       2 failed, 1 passed, 3 total
Snapshots:   2 failed, 1 passed, 3 total
Time:        1.827s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by TrySound** [comment]
@zindel Seems like we should sort modules to get always the same stdout.

**Comment by andreypopp** [comment]
Fixed.
